### ISSUE TITLE
Bug - importing dask-ml.cluster to use KMeans : cannot import name '_ "k_init'" from 'sklearn.cluster._kmeans'

### ISSUE THREAD

**Issue by akarakish1** [dask/dask-ml#780]
Hello all! 

**What happened**:
Failed to import kMeans from dask-ml.cluster using the following code :

```python
from dask_ml.cluster import KMeans
```

Returned error : 

```
cannot import name '_ "k_init'" from 'sklearn.cluster._kmeans'
```

**Environment**:

- Dask version:  dask==2021.1.1, dask-ml==1.7.0
- scikit-learn version : 0.24.1
- Python version: 3.7.5
- Operating System: WSL on windows 10
- Install method (conda, pip, source): pip

The import works fine with scikit-learn  0.23.0.

Regards, 
Ahmed,

**Comment by TomAugspurger** [comment]
It’s fixed on GitHub, but we haven’t made a release yet. Hoping to soon.

**Comment by TomAugspurger** [comment]
Should be fixed in 1.8.0
